# Publishes docs on push
name: Docs
on:
  push:
    branches: [ main ]
    paths:
      - '.optic/api/specification.json'
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
      - uses: actions-js/push@master

      # Runs a set of commands using the runners shell
      - name: Make docs with Optic and Redoc
        run: |
              npm install -g @useoptic/cli redoc-cli
              api generate:oas
              redoc-cli bundle .optic/generated/openapi.yaml
              mv redoc-static.html docs/redoc-static.html
