export interface Word {
  /**
   * The word, in the language.
   */
  word: string
  /**
   * A definition for the word.
   */
  definition: string
  /**
   * The pronunciation of the word in the International Phonetic
   * Alphabet. May later be automatically generated by an SCE ruleset -
   * currently manual.
   */
  ipa?: string
  /**
   * Longer-form notes about the word.
   */
  notes?: string
  /**
   * When this word was created.
   */
  created: Date
  /**
   * When this word was last updated.
   */
  updated: Date
}
