// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./components/BackButton.vue')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CommonButton: typeof import('./components/input/CommonButton.vue')['default']
    CommonSelect: typeof import('./components/input/CommonSelect.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HButton: typeof import('./components/input/HButton.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HMenuButton: typeof import('./components/menu/HMenuButton.vue')['default']
    HMenuItem: typeof import('./components/menu/HMenuItem.vue')['default']
    MdiAccountOutline: typeof import('~icons/mdi/account-outline')['default']
    MdiArrowDown: typeof import('~icons/mdi/arrow-down')['default']
    MdiChatOutline: typeof import('~icons/mdi/chat-outline')['default']
    MdiCheckboxBlank: typeof import('~icons/mdi/checkbox-blank')['default']
    MdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    MdiClose: typeof import('~icons/mdi/close')['default']
    MdiCogOutline: typeof import('~icons/mdi/cog-outline')['default']
    MdiHandWaveOutline: typeof import('~icons/mdi/hand-wave-outline')['default']
    MdiHelpCircleOutline: typeof import('~icons/mdi/help-circle-outline')['default']
    MdiHomeOutline: typeof import('~icons/mdi/home-outline')['default']
    MdiMailboxUpOutline: typeof import('~icons/mdi/mailbox-up-outline')['default']
    MdiMenu: typeof import('~icons/mdi/menu')['default']
    MenuButton: typeof import('./components/menu/MenuButton.vue')['default']
    MenuInner: typeof import('./components/menu/MenuInner.vue')['default']
    MenuItem: typeof import('./components/menu/MenuItem.vue')['default']
    MenuRail: typeof import('./components/menu/MenuRail.vue')['default']
    MenuSection: typeof import('./components/menu/MenuSection.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    PopupMenu: typeof import('./components/PopupMenu.vue')['default']
    ProfilePicture: typeof import('./components/ProfilePicture.vue')['default']
    Scrim: typeof import('./components/Scrim.vue')['default']
    UserMenu: typeof import('./components/UserMenu.vue')['default']
  }
}

export {}
