// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./components/BackButton.vue')['default']
    CommonSelect: typeof import('./components/input/CommonSelect.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    EditProfileDialog: typeof import('./components/EditProfileDialog.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HButton: typeof import('./components/input/HButton.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HInput: typeof import('./components/input/HInput.vue')['default']
    HLink: typeof import('./components/HLink.vue')['default']
    HMenuButton: typeof import('./components/menu/HMenuButton.vue')['default']
    HMenuItem: typeof import('./components/menu/HMenuItem.vue')['default']
    MdiAccount: typeof import('~icons/mdi/account')['default']
    MdiAccountOutline: typeof import('~icons/mdi/account-outline')['default']
    MdiAt: typeof import('~icons/mdi/at')['default']
    MdiChatOutline: typeof import('~icons/mdi/chat-outline')['default']
    MdiClose: typeof import('~icons/mdi/close')['default']
    MdiCogOutline: typeof import('~icons/mdi/cog-outline')['default']
    MdiEye: typeof import('~icons/mdi/eye')['default']
    MdiEyeOff: typeof import('~icons/mdi/eye-off')['default']
    MdiHandWaveOutline: typeof import('~icons/mdi/hand-wave-outline')['default']
    MdiHelpCircleOutline: typeof import('~icons/mdi/help-circle-outline')['default']
    MdiHomeOutline: typeof import('~icons/mdi/home-outline')['default']
    MdiKey: typeof import('~icons/mdi/key')['default']
    MdiMailboxUpOutline: typeof import('~icons/mdi/mailbox-up-outline')['default']
    MdiMenu: typeof import('~icons/mdi/menu')['default']
    MenuInner: typeof import('./components/menu/MenuInner.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    PopupMenu: typeof import('./components/PopupMenu.vue')['default']
    Profile: typeof import('./components/Profile.vue')['default']
    ProfilePicture: typeof import('./components/ProfilePicture.vue')['default']
    Scrim: typeof import('./components/Scrim.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    UserMenu: typeof import('./components/UserMenu.vue')['default']
  }
}

export {}
