/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Drawer: typeof import('./src/components/ui/navigation/Drawer.vue')['default']
    HomeButton: typeof import('./src/components/ui/navigation/HomeButton.vue')['default']
    InvitesButton: typeof import('./src/components/ui/navigation/InvitesButton.vue')['default']
    LanguagesButton: typeof import('./src/components/ui/navigation/LanguagesButton.vue')['default']
    MdiAccount: typeof import('~icons/mdi/account')['default']
    MdiAccountOutline: typeof import('~icons/mdi/account-outline')['default']
    MdiChat: typeof import('~icons/mdi/chat')['default']
    MdiChatOutline: typeof import('~icons/mdi/chat-outline')['default']
    MdiCog: typeof import('~icons/mdi/cog')['default']
    MdiCogOutline: typeof import('~icons/mdi/cog-outline')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiHomeOutline: typeof import('~icons/mdi/home-outline')['default']
    MdiMailbox: typeof import('~icons/mdi/mailbox')['default']
    MdiMailboxOutline: typeof import('~icons/mdi/mailbox-outline')['default']
    MdiMenu: typeof import('~icons/mdi/menu')['default']
    Navigation: typeof import('./src/components/ui/Navigation.vue')['default']
    NavigationExtra: typeof import('./src/components/ui/navigation/NavigationExtra.vue')['default']
    NavigationInner: typeof import('./src/components/ui/navigation/NavigationInner.vue')['default']
    ProfileButton: typeof import('./src/components/ui/navigation/ProfileButton.vue')['default']
    ProfilePicture: typeof import('./src/components/ProfilePicture.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsButton: typeof import('./src/components/ui/navigation/SettingsButton.vue')['default']
    UsersButton: typeof import('./src/components/ui/navigation/UsersButton.vue')['default']
  }
}
