import { env } from 'backend-shared'

export const {
  ANNOUNCEMENTS_API_KEY,
  ANNOUNCEMENTS_PORT,
  ANNOUNCEMENTS_URL,
  DATABASE_URL,
  ENABLE_ANNOUNCEMENTS,
  ENABLE_EVENTS,
  EVENTS_API_KEY,
  EVENTS_PORT,
  EVENTS_URL,
  HANAS_PORT,
  HANAS_URL,
  KRATOS_ADMIN_URL,
  KRATOS_API_KEY,
  KRATOS_PUBLIC_URL,
  NODE_ENV,
  HANAS_RESULTS_DEFAULT_PAGE_SIZE,
  HANAS_RESULTS_MAX_PAGE_SIZE,
} = env
