# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: backend-ci

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/api/**.ts'
      - 'packages/api/**.js'
      - 'packages/api/**.json'
      - 'packages/api/**.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/api/**.ts'
      - 'packages/api/**.js'
      - 'packages/api/**.json'
      - 'packages/api/**.yml'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd packages/api && yarn install --frozen-lockfile
    - run: cd packages/api && yarn run build
    - run: cd packages/api && yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: cd packages/api && yarn install --frozen-lockfile
      - run: cd packages/api && yarn run lint
